// BNF grammar for function signatures

// e.g. [T, Tensor[(..., N, 3), 4]] -> Tensor[(..., N, 3), 4]
// top-level signatures may omit the outer braces accepted by FnType
SignatureType ::= FnType | FnBody;
FnType ::= "{" FnBody "}";
FnBody ::= (ArgList | ArgType) "->" (ArgList | ArgType);

// e.g. '[T, U, Tensor[(N, 3)]]'
ArgList ::= "["  (Arg ("," Arg)*)?  (KeyArg ("," KeyArg)*)?  "]"
Arg ::= ArgType "?"?
KeyArg ::= IdentifierType "?"? "=" ArgType

// e.g. 'T', 'Tensor[...]', 'Foo[Bar, (1,2)]', '{T -> U}'
ArgType ::= ShapeType | IdentifierType | GenericType | FnType

// e.g. '()', '(1,2,3)', '(..., m, n)', '(k,)'
ShapeType ::= "(" ShapeBody? ")"
ShapeBody ::= ("..." | DimType) ("," DimType)* ","?

// Dimension types
DimType ::= ConstantDim | StaticDim | CompoundDim | DynamicDim | VariadicDim
// multiple unknown dimensions (could be one of Constant, Static or Dynamic)
//  "*?"
// e.g. '3': a fixed size dimension
ConstantDim ::= Number
// e.g. 'n': a single axis whose size will be fixed at runtime
StaticDim ::= IdentifierType
// e.g. '$n' a single axes whose size is variable at runtime
DynamicDim ::= "$" IdentifierType
// e.g. '*Xs': a bundle of axes (x₁, ..., xₙ) whose shape will be fixed at runtime
VariadicDim ::= "*" IdentifierType

// e.g. "2n", "3n+3", "n+2", "2u + 3v", "2a + 2b + 2c + 1", "2n - 1"
// affine combination of Static Dims
CompoundDim ::= ConstantDim StaticDim
    | (ConstantDim? StaticDim) (("+" | "-") (ConstantDim? StaticDim))* (("+" | "-") (ConstantDim))
    | (ConstantDim? StaticDim) (("+" | "-") (ConstantDim? StaticDim))+ (("+" | "-") (ConstantDim))?

// e.g. 'Foo[Bar, (1,2)]'
GenericType ::= IdentifierType ArgList

// Basic tokens
IdentifierType ::= Letter (Letter | Digit | '_' )*
Number ::= Digit+ ;
Digit ::= '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' ;
Letter ::= "A" | "B" | "C" | "D" | "E" | "F" | "G"
         | "H" | "I" | "J" | "K" | "L" | "M" | "N"
         | "O" | "P" | "Q" | "R" | "S" | "T" | "U"
         | "V" | "W" | "X" | "Y" | "Z" | "a" | "b"
         | "c" | "d" | "e" | "f" | "g" | "h" | "i"
         | "j" | "k" | "l" | "m" | "n" | "o" | "p"
         | "q" | "r" | "s" | "t" | "u" | "v" | "w"
         | "x" | "y" | "z" ;
