image: python:3.9

stages:
  - setup
  - code analysis
  - documentation
  - unit tests

installtion:
  stage: setup
  script:
  - python setup.py bdist_wheel
#  artifacts:
#    paths:
#    - dist/*.whl

flake8:
  stage: code analysis
  allow_failure: true
  before_script:
    - pip install flake8
  script:
    - flake8 --max-line-length=100 --ignore=E203,E221,E226,E241 linodenet

pylint:
  stage: code analysis
  allow_failure: true
  before_script:
      - pip install pylint pylint-exit anybadge
  script:
    - mkdir ./pylint
    - pylint linodenet --generated-members=numpy.*,torch.* --disable=C0103,C0144 --output-firmat=text | tee ./pylint/pylint.log || pylint-exit $?
    - PYLINT_SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' ./pylint/pylint.log)
    - anybadge --label=Pylint --file=pylint/pylint.svg --value=$PYLINT_SCORE 2=red 4=orange 8=yellow 10=green
    - echo "Pylint score is $PYLINT_SCORE"
  artifacts:
    paths:
      - ./pylint/


pages:
  stage: documentation
  allow_failure: true
  script:
    - pip install -U sphinx sphinx-rtd-theme sphinx-math-dollar
    - cd docs
    - make html
    - mv _build/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - master

tox:
  stage: unit tests
  allow_failure: true
  before_script:
    - pip install tox
  script:
    echo "tox --recreate"