interfaces = []
exclude = [
    "**/*__pycache__",
    "**/*egg-info",
    "**/docs",
    "**/tests",
    "**/venv",
]
source_roots = ["src"]

[[modules]]
path = "blueprint"
depends_on = []
utility = true

[[modules]]
path = "signatures"
depends_on = []
utility = true

[[modules]]
path = "imtskit_special"
depends_on = []

[[modules]]
path = "imtskit_models"
depends_on = ["imtskit.state_update"]

[[modules]]
path = "imtskit"
depends_on = [
    "imtskit.distributions",
    "imtskit.initializations",
    "imtskit.state_update",
    "imtskit.forecasting",
    "imtskit.nn",
    "imtskit.parametrizations",
    "imtskit.regularizations",
    "imtskit.domains",
    "imtskit.mappings",
    "imtskit.state_propagation",
    "imtskit.state_update.imputation",
    "imtskit_models",
]

[[modules]]
path = "imtskit.constants"
depends_on = []
utility = true

[[modules]]
path = "imtskit.utils"
depends_on = []
utility = true

[[modules]]
path = "imtskit.types"
depends_on = []
utility = true

[[modules]]
path = "imtskit.testing"
depends_on = []
utility = true

[[modules]]
path = "imtskit.registry"
depends_on = [
    "imtskit.parametrizations",
    "imtskit.regularizations",
    "imtskit.domains",
    "imtskit.initializations",
    "imtskit.mappings",
]
utility = true

[[modules]]
path = "imtskit.special"
depends_on = ["imtskit_special"]
utility = true

[[modules]]
path = "imtskit.initializations"
depends_on = [
    "imtskit.domains",
]

[[modules]]
path = "imtskit.nn"
depends_on = []

[[modules]]
path = "imtskit.forecasting"
depends_on = [
    "imtskit.nn",
    "imtskit.mappings",
    "imtskit.state_propagation",
]

[[modules]]
path = "imtskit.regularizations"
depends_on = ["imtskit.mappings"]

[[modules]]
path = "imtskit.domains"
depends_on = []

[[modules]]
path = "imtskit.distributions"
depends_on = [
    "imtskit.nn",
    "imtskit.domains",
]

[[modules]]
path = "imtskit.mappings"
depends_on = [
    "imtskit.nn",
    "imtskit.domains",
    "imtskit_special",
]

[[modules]]
path = "imtskit.parametrizations"
depends_on = [
    "imtskit.nn",
    "imtskit.mappings",
    "imtskit.domains",
]

[[modules]]
path = "imtskit.state_propagation"
depends_on = [
    "imtskit.mappings",
    "imtskit.initializations",
    "imtskit.nn",
    "imtskit.parametrizations",
]

[[modules]]
path = "imtskit.state_update"
depends_on = [
    "imtskit.distributions",
    "imtskit.nn",
    "imtskit.state_update.imputation",
    "imtskit.mappings",
]

[[modules]]
path = "imtskit.state_update.imputation"
depends_on = []
