interfaces = []
exclude = [
    "**/*__pycache__",
    "**/*egg-info",
    "**/docs",
    "**/tests",
    "**/venv",
]
source_roots = [ "src",
]

[[modules ]]
path = "linodenet.nn"
depends_on = [ "linodenet_special"]

[[modules ]]
path = "linodenet.utils"
depends_on = []
utility = true

[[modules ]]
path = "linodenet.initializations"
depends_on = ["linodenet.domains"]

[[modules ]]
path = "linodenet.constants"
depends_on = []
utility = true

[[modules ]]
path = "linodenet.forecasting"
depends_on = [ "linodenet.nn", "linodenet_special", "linodenet.mappings", "linodenet.state_update", "linodenet.state_propagation"]

[[modules ]]
path = "linodenet.regularizations"
depends_on = [ "linodenet.mappings"]

[[modules ]]
path = "linodenet.types"
depends_on = []
utility = true

[[modules ]]
path = "linodenet.testing"
depends_on = []

[[modules ]]
path = "linodenet.domains"
depends_on = []

[[modules ]]
path = "linodenet.distributions"
depends_on = ["linodenet.nn"]

[[modules ]]
path = "blueprint"
depends_on = []
utility = true

[[modules ]]
path = "linodenet"
depends_on = ["linodenet.distributions", "linodenet.initializations", "linodenet_special", "linodenet.state_update", "linodenet.forecasting", "linodenet.nn", "linodenet.testing", "linodenet.parametrizations", "linodenet.regularizations", "linodenet.domains", "linodenet.mappings", "linodenet.state_propagation", "linodenet.state_update.imputation"]

[[modules ]]
path = "signatures"
depends_on = []
utility = true

[[modules ]]
path = "linodenet_special"
depends_on = ["linodenet_special.fallbacks", "linodenet_special.kernels", "linodenet_special.interfaces"]

[[modules ]]
path = "linodenet_special.fallbacks"
depends_on = ["linodenet_special.interfaces"]

[[modules ]]
path = "linodenet_special.interfaces"
depends_on = []

[[modules ]]
path = "linodenet_special.kernels"
depends_on = [ "linodenet_special.fallbacks", "linodenet_special.compiled", "linodenet_special.interfaces"]

[[modules ]]
path = "linodenet_special.compiled"
depends_on = ["linodenet_special.interfaces"]

[[modules ]]
path = "linodenet.mappings"
depends_on = ["linodenet_special.fallbacks", "linodenet.nn", "linodenet_special", "linodenet.domains"]

[[modules ]]
path = "linodenet.parametrizations"
depends_on = ["linodenet.nn", "linodenet.mappings", "linodenet.domains"]

[[modules ]]
path = "linodenet.registry"
depends_on = ["linodenet.parametrizations", "linodenet.regularizations", "linodenet.domains", "linodenet.initializations", "linodenet.mappings"]
utility = true

[[modules ]]
path = "linodenet.state_propagation"
depends_on = ["linodenet.mappings", "linodenet.initializations"]

[[modules ]]
path = "linodenet.state_update"
depends_on = ["linodenet.distributions", "linodenet.nn", "linodenet.state_update.imputation"]

[[modules ]]
path = "linodenet.state_update.imputation"
depends_on = []
