interfaces = []
exclude = [
    "**/*__pycache__",
    "**/*egg-info",
    "**/docs",
    "**/tests",
    "**/venv",
]
source_roots = [ "src",
]

[[modules ]]
path = "linodenet.nn"
depends_on = [ "linodenet.nn.activations", "linodenet.lib", "linodenet.nn.embeddings", "linodenet.nn.containers"]

[[modules ]]
path = "linodenet.utils"
depends_on = []
utility = true

[[modules ]]
path = "linodenet.filters"
depends_on = [ "linodenet.distributions", "linodenet.imputation", "blueprint", "linodenet.nn"]

[[modules ]]
path = "linodenet.initializations"
depends_on = []

[[modules ]]
path = "linodenet.constants"
depends_on = []
utility = true

[[modules ]]
path = "linodenet.forecasting"
depends_on = ["linodenet.filters", "linodenet.projections", "blueprint", "linodenet.lib", "linodenet.flows", "linodenet.nn", "linodenet.nn.embeddings"]

[[modules ]]
path = "linodenet.regularizations"
depends_on = [ "linodenet.projections"]

[[modules ]]
path = "linodenet.imputation"
depends_on = []

[[modules ]]
path = "linodenet.lib"
depends_on = []

[[modules ]]
path = "linodenet.projections"
depends_on = []

[[modules ]]
path = "linodenet.types"
depends_on = []
utility = true

[[modules ]]
path = "linodenet.testing"
depends_on = []

[[modules ]]
path = "linodenet.bijections"
depends_on = [ "linodenet.initializations", "linodenet.nn", "linodenet.nn.activations"]

[[modules ]]
path = "linodenet.parametrize"
depends_on = ["linodenet.projections", "linodenet.testing", "linodenet.lib", "linodenet.nn"]

[[modules ]]
path = "linodenet.domains"
depends_on = []
utility = true

[[modules ]]
path = "linodenet.distributions"
depends_on = ["linodenet.nn"]

[[modules ]]
path = "linodenet.signatures"
depends_on = []
utility = true

[[modules ]]
path = "blueprint"
depends_on = []

[[modules ]]
path = "linodenet.flows"
depends_on = ["linodenet.projections", "linodenet.initializations"]

[[modules ]]
path = "linodenet.nn.embeddings"
depends_on = []

[[modules ]]
path = "linodenet.nn.activations"
depends_on = ["blueprint"]

[[modules ]]
path = "linodenet.nn.containers"
depends_on = []
