#!/usr/bin/env just --justfile

[default]
[doc('List available commands.')]
help:
    @just --justfile {{ justfile() }} --list --unsorted

[doc('Profile tsdm import time with tuna.')]
time-imports:
    #!/usr/bin/env bash
    dependencies=(
      numpy
      torch
      torchode
    )
    # get project root with git
    cd "$(git rev-parse --show-toplevel)" || exit
    echo "Project root: $(pwd)"
    IFS=,
    uv run python -X importtime -c \
      "import ${dependencies[*]}; import linodenet" \
      2> tests/import_time.log
    uv run tuna tests/import_time.log
