SignatureType ::= (ArgList | ArgType) "->" (ArgList | ArgType)

ArgList ::= "[" (ArgType ("," ArgType)*)? "]"

(* e.g. T, Tensor[...], Foo[Bar, (1,2)] *)
ArgType ::= ShapeType | IdentifierType | GenericType

(* e.g. (), (1,2,3), (..., m, n) *)
ShapeType ::= "(" ( ("..." | DimType) ("," DimType)*)? ")"

(* e.g. 'N', '*Batch', '**xs' *)
DimType ::= IntegerLiteral | ("*" | "**")? IdentifierType

GenericType ::= IdentifierType ArgList
IdentifierType ::= /[A-Za-z]\w*/
IntegerLiteral ::= /\d+/
