BUILD_DIR := "./_build"

[default]
[doc('Show documentation commands.')]
help:
    @just --justfile {{ justfile() }} --list docs

[doc('Clean Sphinx build artifacts.')]
clean:
    #!/usr/bin/env bash
    set -eu

    export PYTORCH_JIT=0

    mkdir -p "{{ BUILD_DIR }}"
    rm -rf _previous_build
    mv "{{ BUILD_DIR }}" _previous_build

    rm -rf "{{ BUILD_DIR }}"
    rm -rf _autosummary
    rm -rf autoapi
    rm -rf apidoc
    rm -rf api

[doc('Rebuild the Sphinx API docs and HTML output.')]
make *sphinx_args: clean
    #!/usr/bin/env bash
    set -eu

    export PYTORCH_JIT=0
    VENV="../.venv/bin/activate"
    sphinx_opts=(-w .sphinx/warnings.txt)

    . "${VENV}"
    sphinx-apidoc --separate -o apidoc/ ../src/linodenet
    sphinx-build -M html . "{{ BUILD_DIR }}" "${sphinx_opts[@]}" {{sphinx_args}}
