[project]
docs_dir = "zensical"
site_dir = "build/zensical"
site_name = "imtskit"
site_description = "Irregular Multivariate Time Series Toolkit"
site_url = "https://github.com/randolf-scholz/imtskit"
site_author = "Randolf Scholz"
repo_url = "https://github.com/randolf-scholz/imtskit"
repo_name = "randolf-scholz/imtskit"
extra_css = ["_static/footer-navigation.css", "_static/signatures.css"]

# The configuration must be loaded before the MathJax runtime.
extra_javascript = [
    "_static/mathjax_config.js",
    "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js",
]

nav = [
    { "Home" = "index.md" },
    { "API reference" = "reference/" },
]

[project.theme]
custom_dir = "zensical/_templates"
language = "en"
features = [
    "content.code.copy",
    # "navigation.footer",
    "navigation.indexes",
    "navigation.sections",
    "navigation.tabs",
    "navigation.top",
    "search.highlight",
    "search.suggest",
    "toc.follow",
]

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[project.plugins.mkdocstrings]
default_handler = "python"

[project.plugins.literate-nav]
nav_file = "SUMMARY.md"

[project.plugins.mkdocstrings.handlers.python]
paths = ["../src"]
inventories = [
    "https://numpy.org/doc/stable/objects.inv",
    "https://docs.pytest.org/en/stable/objects.inv",
    "https://docs.python.org/3/objects.inv",
    "https://docs.scipy.org/doc/scipy/objects.inv",
    "https://docs.pytorch.org/docs/stable/objects.inv",
    "https://typing-extensions.readthedocs.io/en/latest/objects.inv",
]

[project.plugins.mkdocstrings.handlers.python.options]
# general
show_source = true
# headings
heading_level = 1
parameter_headings = true
show_root_full_path = false
show_root_heading = true
show_symbol_type_heading = true
show_symbol_type_toc = true
# members
members = false
members_order = "source"
show_submodules = false
# docstrings
docstring_style = "google"
docstring_section_style = "list"
docstring_options = {
    ignore_init_summary = true,
    trim_doctest_flags = true
}
# signatures
line_length = 88
overloads_only = true
separate_signature = true
show_signature_annotations = true
signature_crossrefs = true
type_parameter_headings = true

[project.markdown_extensions]
admonition = { }
attr_list = { }
md_in_html = { }
toc.permalink = true
pymdownx.arithmatex.generic = true
pymdownx.details = { }
pymdownx.highlight.anchor_linenums = true
pymdownx.highlight.line_spans = "__span"
pymdownx.highlight.pygments_lang_class = true
pymdownx.inlinehilite = { }
pymdownx.snippets = { }
pymdownx.superfences = { }
pymdownx.tabbed.alternate_style = true
